[build]
  command = "npm install --legacy-peer-deps && npx prisma generate && npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_PRODUCTION = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"

[context.deploy-preview]
  command = "npm install --legacy-peer-deps && npm run build"

[context.branch-deploy]
  command = "npm install --legacy-peer-deps && npm run build"

# Optional redirects
[[redirects]]
  from = "/old-route"
  to = "/new-route"
  status = 301

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200
